name: flutter_universal_demo
description: Universal Flutter Demo Project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  dio: ^5.0.6
  amap_flutter_map: ^3.0.0
  auto_route: ^5.0.4
  carousel_slider: ^5.1.1
  flutter_localizations:
    sdk: flutter
  qr_code_scanner: ^1.0.0
  share_plus: ^12.0.1
  screenshot: ^3.0.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  auto_route_generator: ^5.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
